import { Header, MethodSteps, PageMotion } from "./interactive";
import { TransformationCarousel } from "./transformations";
import { VerifiedAuthority, VerifiedGuarantee, VerifiedTestimonials } from "./verified-content";
import Image, { getImageProps } from "next/image";
import methodLogo from "../public/logo-metodo.webp";
import methodLogoDark from "../public/logo-metodo-escuro.webp";
import rosePortrait from "../public/imagem-rose.webp";
import platformMockup from "../public/mockup-plataforma.webp";
import { MirrorVideo } from "./mirror-video";

const hotmart = "https://pay.hotmart.com/J93330857K?sck=HOTMART_PRODUCT_PAGE&off=dge3oat7&hotfeature=32&_gl=1*1lc81pl*_gcl_au*MjAxNDE5OTAzOC4xNzg5MDc1MzcxLi0uLS4xNzg5NTU5MTU0LjIwNzcxMDIyMTguMTc5MDM1ODE5MS4xNzkwMzU5NTAx*_ga*MTA2NzI0MzQuMTc4OTA3NTM3MA..*_ga_GQH2V1F11Q*czE3OTA2Nzg2MjAkbzY0JGcxJHQxNzkwNjgxNjAxJGo2MCRsMCRoNzIxMTMzMzAw&bid=1790681605157";

function ArrowLink({ href, children, light = false, external = false }: { href: string; children: React.ReactNode; light?: boolean; external?: boolean }) {
  return <a className={`button ${light ? "button-light" : ""}`} href={href} {...(external ? { target: "_blank", rel: "noopener noreferrer" } : {})}>{children}<span aria-hidden="true">↗</span></a>;
}

export default function Home() {
  const { props: desktopHero } = getImageProps({ src: "/banner-hero-desktop.webp", alt: "Rose Oliveira sorrindo, com cabelos loiros e roupa preta", fill: true, sizes: "100vw", unoptimized: true, loading: "eager", fetchPriority: "high" });
  const { props: mobileHero } = getImageProps({ src: "/banner-hero-mobile.webp", alt: "", fill: true, sizes: "100vw", unoptimized: true });
  return <>
    <Header />
    <PageMotion />
    <main id="inicio">
      <section className="hero" aria-labelledby="hero-title">
        <picture className="hero-picture"><source media="(max-width: 600px)" srcSet={mobileHero.srcSet ?? mobileHero.src} sizes="100vw" /><img {...desktopHero} alt="Rose Oliveira sorrindo, com cabelos loiros e roupa preta" className="hero-image" /></picture>
        <div className="hero-wash" aria-hidden="true" />
        <div className="hero-content wrap">
          <span className="hero-overline">MÉTODO ROSE OLIVEIRA <span>—</span> MECHAS COM INTENÇÃO</span>
          <h1 id="hero-title"><em>Transforme</em> sua técnica.<br /><em>Transforme</em> seus resultados.<br /><em>Transforme</em> o seu valor.</h1>
          <p>O método em que Rose Oliveira te ensina, de forma simples e prática, o processo por trás de mechas que encantam clientes e valorizam o seu trabalho.</p>
          <div className="hero-actions"><ArrowLink href={hotmart} external>Quero aprender com a Rose</ArrowLink><a className="scroll-cue" href="#transformacao" aria-label="Rolar para conhecer a transformação"><span className="scroll-cue-track" aria-hidden="true"><span /></span><span aria-hidden="true">ROLE PARA EXPLORAR</span></a></div>
          <span className="hero-footnote">DO ATENDIMENTO À FINALIZAÇÃO</span>
        </div>
        <div className="hero-rail">MECHAS <b>·</b> TÉCNICA <b>·</b> EXPERIÊNCIA <b>·</b> RESULTADO</div>
      </section>

      <div className="marquee" aria-label="Técnica, segurança, resultado, valorização, transformação, mechas, experiência"><div className="marquee-track" aria-hidden="true">{Array.from({ length: 4 }, (_, i) => <span key={i}>TÉCNICA <i>·</i> SEGURANÇA <i>·</i> RESULTADO <i>·</i> VALORIZAÇÃO <i>·</i> TRANSFORMAÇÃO <i>·</i> MECHAS <i>·</i> EXPERIÊNCIA <i>·</i> </span>)}</div></div>

      <section className="intro section-pad" id="transformacao">
        <div className="wrap intro-grid"><div><span className="eyebrow">NÃO É SÓ SOBRE CABELO.</span><h2>Quando a técnica muda, <em>tudo ao redor</em> do seu trabalho começa a mudar também.</h2></div><div className="intro-side"><p>Um resultado bonito não começa na finalização. Ele começa na forma como você analisa, planeja, executa, atende e conduz cada etapa.</p><div className="transformation-line"><span>Insegurança</span><b>→</b><span>Método</span><b>→</b><span>Domínio</span><b>→</b><span>Resultado</span><b>→</b><span>Valorização</span></div></div></div>
        <div className="giant-type" aria-hidden="true">TRANSFORMAÇÃO</div>
      </section>

      <section className="mirror" aria-labelledby="mirror-title"><MirrorVideo /><div className="mirror-copy"><span className="eyebrow">O MOMENTO QUE IMPORTA</span><h2 id="mirror-title">Existe um momento em que a cliente se olha no espelho e percebe que não saiu apenas com um cabelo diferente.</h2><p className="mirror-punch">Ela se sente diferente.</p><p>É esse nível de transformação que a Rose construiu na cadeira do salão — e é esse olhar que ela quer ensinar você a desenvolver.</p></div></section>

      <section className="portfolio section-pad" id="resultados"><div className="wrap"><div className="section-heading"><div><span className="eyebrow">O TRABALHO FALA</span><h2>Resultados que falam <em>antes da explicação.</em></h2></div><p>Cada cabelo carrega diagnóstico, escolha, técnica e intenção.</p></div><TransformationCarousel /><p className="asset-note">Os pares serão publicados aqui com os registros reais e autorizados da Rose Oliveira.</p></div></section>

      <section className="objection section-pad"><div className="wrap"><h2>Talvez você já saiba fazer mechas.<br /><em>O que está faltando é entender o processo.</em></h2><div className="compare"><div><span className="eyebrow">QUANDO FALTA UM MÉTODO</span><ul><li>Insegurança na escolha da técnica</li><li>Medo de comprometer o resultado</li><li>Dificuldade para reproduzir resultados</li><li>Processo sem padrão</li><li>Sensação de estar sempre improvisando</li></ul></div><div><span className="eyebrow">O QUE UM MÉTODO PODE TE AJUDAR A CONSTRUIR</span><ul><li>Mais clareza nas decisões</li><li>Planejamento antes da execução</li><li>Um processo que você entende</li><li>Busca por mais consistência</li><li>Confiança para conduzir cada etapa</li></ul></div></div></div></section>

      <section className="method section-pad" id="metodo"><div className="wrap method-grid"><div className="method-intro"><span className="eyebrow">DO PRIMEIRO OLHAR AO ÚLTIMO DETALHE</span><h2 className="method-logo"><Image src={methodLogo} alt="Método Rose Oliveira" sizes="(max-width: 800px) 88vw, 40vw" unoptimized /></h2><p className="large-copy">Mais do que repetir uma técnica: entender o raciocínio por trás do resultado.</p><p>Do atendimento à finalização, você acompanha o processo de uma forma simples e prática.</p><a className="text-link" href="#oferta">Conhecer o método <span aria-hidden="true">↗</span></a></div><MethodSteps /></div><div className="method-watermark" aria-hidden="true">MÉTODO</div></section>

      <section className="learning section-pad" id="aprendizado"><div className="wrap"><div className="learning-title"><span className="eyebrow">O QUE VOCÊ DESENVOLVE</span><h2>Você não precisa apenas saber o que fazer.<br /><em>Precisa entender por que fazer.</em></h2></div><div className="learning-list"><article className="learning-item"><span>01 / OLHAR PROFISSIONAL</span><h3>Antes da técnica,<br />vem o olhar.</h3><p>Entender melhor o cabelo antes de começar.</p></article><article className="learning-item"><span>02 / PROCESSO</span><h3>Menos improviso.<br />Mais direção.</h3><p>Organizar a execução com mais clareza.</p></article><article className="learning-item"><span>03 / RESULTADO</span><h3>Intenção em<br />cada escolha.</h3><p>Buscar mais consistência em cada trabalho.</p></article><article className="learning-item"><span>04 / VALOR</span><h3>Seu trabalho<br />merece ser visto.</h3><p>Construir um serviço que comunique profissionalismo.</p></article></div></div></section>

      <section className="business section-pad"><div className="wrap business-grid"><div><span className="eyebrow">MECHAS LUCRATIVAS, SEM PROMESSAS FÁCEIS</span><h2>Uma técnica bonita também precisa fazer sentido para <em>o seu negócio.</em></h2><p>Não basta entregar um resultado incrível se o processo consome tempo, gera insegurança ou faz você ter dificuldade para perceber o valor do próprio serviço.</p></div><div className="equation"><span>TÉCNICA</span><i>+</i><span>PROCESSO</span><i>+</i><span>EXPERIÊNCIA</span><i>=</i><strong>SERVIÇO MAIS VALORIZADO</strong></div></div></section>

      <section className="mentor" id="rose"><div className="mentor-photo"><Image src={rosePortrait} alt="Rose Oliveira sentada, sorrindo, em um ambiente claro" fill sizes="(max-width: 800px) 100vw, 50vw" unoptimized /></div><div className="mentor-copy"><span className="eyebrow">QUEM VAI TE ENSINAR</span><h2>Antes de ensinar transformação, Rose construiu transformação <em>todos os dias.</em></h2><div className="mentor-story"><p>Antes de me tornar a Rose Oliveira que sou hoje, eu trabalhava como babá durante a semana e auxiliar em um salão de beleza nos fins de semana. No salão, eu me sentia realizada, mesmo que minha função fosse apenas lavar cabelos. Eu adorava aquele ambiente e, sendo sempre muito curiosa, logo aprendi a escovar cabelos rapidamente.</p><p>Porém, quando via uma cliente chegando com mechas no cabelo, meus olhos brilhavam. Achava aquilo incrível, era meu sonho ter mechas no meu cabelo. Um dia, a dona do salão realizou meu sonho. Naquela época, a moda eram aquelas mechas bem marcadas, estilo zebra (risos).</p><p>Eu observava cada detalhe e decidi fazer na minha cunhada. Ela comprou os materiais no mercadinho próximo à casa dela, e eu, mesmo sem conhecimento e usando os recursos que tinha, fiz. Quando terminei, ela ficou tão feliz que me empolgou ainda mais. Ao ver a reação dela, ansiei por mostrar o novo visual a todos. Fiquei maravilhada e com a certeza em meu coração de que queria fazer isso mais vezes. E nunca mais parei.</p><p>Foi aí que decidi me desenvolver e me capacitar dia após dia. Hoje, transformo vidas através das transformações. Por isso, digo com propriedade que trabalhar com mechas mudou minha realidade e a da minha família.</p><p>Agora, quero mudar a sua vida também, entregando não apenas um curso de mechas, mas sim um método que desenvolvi ao longo da minha jornada. Nele, você aprenderá a desenvolver suas habilidades e explorar o talento que Deus te deu. Vem comigo nesta jornada de sucesso!</p></div><span className="mentor-signature">Rose Oliveira</span><a className="text-link" href="https://www.instagram.com/roseoliveirahair" target="_blank" rel="noopener noreferrer">Conheça a Rose no Instagram <span aria-hidden="true">↗</span></a></div></section>

      <VerifiedAuthority />
      <VerifiedTestimonials />
      <section className="audience section-pad" id="para-quem"><div className="wrap audience-grid"><div><span className="eyebrow">SE VOCÊ SE RECONHECE AQUI</span><h2>Esse método é <em>para você que...</em></h2></div><div className="audience-lines"><p>...quer deixar de trabalhar no improviso.</p><p>...quer entender melhor cada etapa do processo.</p><p>...quer construir resultados mais consistentes.</p><p>...quer se sentir mais segura diante da cliente.</p><p>...quer elevar sua técnica e a percepção de valor do seu trabalho.</p><p>...quer aprender com uma profissional que vive essa realidade.</p></div></div><div className="wrap audience-close">Você não precisa saber tudo.<br /><em>Precisa decidir parar de fazer tudo sozinha.</em></div></section>

      <section className="content section-pad" id="conteudo"><div className="wrap content-grid"><div><span className="eyebrow">O CONTEÚDO</span><h2>Por dentro do <em>Método Rose Oliveira.</em></h2><p>O detalhamento das aulas será publicado aqui assim que o programa oficial for disponibilizado.</p></div><div className="content-accordion"><details><summary><span>CONTEÚDO 01</span><b>Atendimento à cliente</b><i aria-hidden="true">+</i></summary><p>O método aborda o atendimento à cliente. [ADICIONAR CONTEÚDO REAL DAS AULAS]</p></details><details><summary><span>CONTEÚDO 02</span><b>Processo de mechas</b><i aria-hidden="true">+</i></summary><p>O método aborda mechas de forma simples e prática. [ADICIONAR CONTEÚDO REAL DAS AULAS]</p></details><details><summary><span>CONTEÚDO 03</span><b>Finalização</b><i aria-hidden="true">+</i></summary><p>O método acompanha o processo até a finalização. [ADICIONAR CONTEÚDO REAL DAS AULAS]</p></details></div></div></section>

      <section className="experience section-pad"><div className="wrap experience-grid"><figure className="platform-figure"><Image src={platformMockup} alt="Mockup ilustrativo do Método Rose Oliveira em notebook e celular" sizes="(max-width: 800px) 100vw, 55vw" unoptimized /><figcaption>Imagem ilustrativa. Telas, módulos e recursos exibidos no mockup devem ser confirmados no produto oficial.</figcaption></figure><div><span className="eyebrow">A EXPERIÊNCIA DE APRENDER</span><h2>Aprenda onde estiver.<br /><em>Aplique onde importa.</em></h2><p>Conteúdo digital pensado para você evoluir no seu ritmo e levar o aprendizado para a prática.</p></div></div></section>

      <section className="offer section-pad" id="oferta"><div className="wrap offer-grid"><div className="offer-art"><span>O PRÓXIMO CAPÍTULO</span><div className="offer-logo-frame"><Image src={methodLogoDark} alt="Método Rose Oliveira" sizes="(max-width: 800px) 80vw, 36vw" unoptimized /></div><small>ATENDIMENTO · MECHAS · FINALIZAÇÃO</small></div><div className="offer-copy"><span className="eyebrow">SUA PRÓXIMA ETAPA COMEÇA AQUI</span><h2>Método<br /><em>Rose Oliveira.</em></h2><p>Um caminho para sair da tentativa e erro e desenvolver mais intenção em cada resultado.</p><ul><li>Processo do atendimento à finalização</li><li>Ensino simples e prático</li><li>Foco em mechas</li><li>Acompanhamento da Rose durante a jornada</li></ul><ArrowLink href={hotmart} external>Quero entrar para o método</ArrowLink><small>Compra processada pela Hotmart.</small></div></div></section>

      <VerifiedGuarantee />
      <section className="faq section-pad" id="duvidas"><div className="wrap faq-grid"><div><span className="eyebrow">ANTES DE COMEÇAR</span><h2>Algumas respostas para você seguir <em>com clareza.</em></h2></div><div className="faq-list"><details><summary>Para quem é o Método Rose Oliveira?<span aria-hidden="true">+</span></summary><p>Para profissionais e futuras profissionais que desejam desenvolver técnica, clareza e intenção no trabalho com mechas, do atendimento à finalização.</p></details><details><summary>Preciso já trabalhar com cabelo?<span aria-hidden="true">+</span></summary><p>A descrição pública do treinamento não estabelece pré-requisitos. Consulte as informações oficiais na Hotmart antes de realizar a compra.</p></details><details><summary>Como vou acessar o treinamento?<span aria-hidden="true">+</span></summary><p>O Método Rose Oliveira é um produto digital comercializado pela Hotmart. As instruções específicas de acesso devem ser confirmadas na página oficial do produto.</p></details><details><summary>Consigo assistir pelo celular?<span aria-hidden="true">+</span></summary><p>Confira os dispositivos compatíveis na página oficial da Hotmart antes da compra.</p></details><details><summary>Por quanto tempo terei acesso? Existe garantia?<span aria-hidden="true">+</span></summary><p>Prazo de acesso e condições de garantia não foram informados nos materiais disponíveis. Consulte as condições exibidas pela Hotmart no momento da compra.</p></details><details><summary>Existe acompanhamento?<span aria-hidden="true">+</span></summary><p>Na descrição pública do produto, Rose informa que acompanhará as alunas como mentora durante a jornada. Para detalhes sobre o formato, consulte a página oficial.</p></details></div></div></section>

      <section className="final-cta"><div className="final-ghost" aria-hidden="true">ROSE</div><div className="wrap final-content"><span className="eyebrow">TRANSFORMAÇÃO QUE PASSA ADIANTE</span><h2>Quantas clientes ainda vão se olhar no espelho e se sentir diferentes por causa de uma técnica que você decidiu aprender hoje?</h2><p>Comece a próxima fase da sua profissão com o Método Rose Oliveira.</p><ArrowLink href={hotmart} light external>Quero começar minha transformação</ArrowLink><div className="final-logo"><Image src={methodLogoDark} alt="Método Rose Oliveira" sizes="240px" unoptimized /></div></div></section>
    </main>
    <footer className="footer"><div className="wrap footer-main"><div><a href="#inicio" className="footer-logo" aria-label="Método Rose Oliveira — voltar ao início"><Image src={methodLogoDark} alt="Método Rose Oliveira" sizes="240px" unoptimized /></a><p>Transformação que passa adiante.</p></div><div><a href="https://www.instagram.com/roseoliveirahair" target="_blank" rel="noopener noreferrer">@roseoliveirahair ↗</a><span>Contato: inserir canal oficial</span></div></div><div className="wrap footer-bottom"><span>O produto é comercializado através da plataforma Hotmart.</span><span>Termos e privacidade: consultar as condições na Hotmart.</span></div></footer>
  </>;
}
